<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="en" target-language="ru" datatype="htmlbody" original="https://pypi.org/project/pycheops/">
    <body>
      <group id="pycheops">
        <trans-unit id="f1603d521808f158186cc68afb235430e8216c34" translate="yes" xml:space="preserve">
          <source>&amp;ldquo;No matching distribution found for matplotlib&amp;gt;3,2 (from pycheops)&amp;rdquo;</source>
          <target state="translated">&amp;laquo;Не найдено подходящего распределения для matplotlib&amp;gt; 3,2 (от pycheops)&amp;raquo;</target>
        </trans-unit>
        <trans-unit id="5dd5599aa0661138fac4e54a2ad7d4390c685267" translate="yes" xml:space="preserve">
          <source>&amp;ldquo;TypeError: &amp;lsquo;str&amp;rsquo; object is not callable&amp;rdquo; in animate frames</source>
          <target state="translated">&amp;laquo;TypeError: объект 'str' не вызывается&amp;raquo; в кадрах анимации</target>
        </trans-unit>
        <trans-unit id="930634090215011d3fafe673f03eca7ee4c23fb6" translate="yes" xml:space="preserve">
          <source>&amp;ldquo;conda update &amp;ndash;all&amp;rdquo; then &amp;ldquo;pip install pycheops &amp;ndash;upgrade&amp;rdquo;</source>
          <target state="translated">&amp;laquo;Conda update &amp;ndash;all&amp;raquo;, затем &amp;laquo;pip install pycheops &amp;ndash;upgrade&amp;raquo;</target>
        </trans-unit>
        <trans-unit id="eb810f9c8fe03f2f3eac98788ce4ab3f34b6d152" translate="yes" xml:space="preserve">
          <source>&amp;ldquo;pip install matplotlib &amp;ndash;upgrade&amp;rdquo; then &amp;ldquo;pip install pycheops &amp;ndash;upgrade&amp;rdquo;</source>
          <target state="translated">&amp;laquo;Pip install matplotlib &amp;ndash;upgrade&amp;raquo;, затем &amp;laquo;pip install pycheops &amp;ndash;upgrade&amp;raquo;</target>
        </trans-unit>
        <trans-unit id="763e13fbb5e11a148c6e753ca9e4e3d0b8cbf233" translate="yes" xml:space="preserve">
          <source>CHEOPS light curve analysis software</source>
          <target state="translated">программное обеспечение для анализа кривых блеска CHEOPS</target>
        </trans-unit>
        <trans-unit id="3414d1ef796b45b8b78636cc7dc0d00485e20ff9" translate="yes" xml:space="preserve">
          <source>For discussion and announcements, please join the &lt;a href=&quot;https://groups.google.com/forum/#!forum/pycheops&quot;&gt;pycheops google group&lt;/a&gt;</source>
          <target state="translated">Для обсуждения и объявлений присоединяйтесь к группе &lt;a href=&quot;https://groups.google.com/forum/#!forum/pycheops&quot;&gt;pycheops google&lt;/a&gt;</target>
        </trans-unit>
        <trans-unit id="1605b302b4f14fef72c2f2b293539ce45c4cec5b" translate="yes" xml:space="preserve">
          <source>Install &amp;ldquo;pillow&amp;rdquo;, e.g., conda install pillow.</source>
          <target state="translated">Установите &amp;laquo;подушку&amp;raquo;, например, установите подушку conda.</target>
        </trans-unit>
        <trans-unit id="7ab62122bb2dfe3b61ac8bfc91d110f16ce0d7b4" translate="yes" xml:space="preserve">
          <source>Installation fails with &amp;ldquo;ModuleNotFoundError: No module named &amp;lsquo;pybind11&amp;rsquo;&amp;rdquo;</source>
          <target state="translated">Ошибка установки: &amp;laquo;ModuleNotFoundError: нет модуля с именем 'pybind11'&amp;raquo;</target>
        </trans-unit>
        <trans-unit id="e085eda5031b722f6498d726b7bcf078ef13852c" translate="yes" xml:space="preserve">
          <source>Python package for the analysis of light curves from the &lt;a href=&quot;http://cheops.unibe.ch/&quot;&gt;ESA CHEOPS mission&lt;/a&gt;.</source>
          <target state="translated">Пакет Python для анализа кривых &lt;a href=&quot;http://cheops.unibe.ch/&quot;&gt;блеска миссии ESA CHEOPS&lt;/a&gt; .</target>
        </trans-unit>
        <trans-unit id="b1b392607deaf29a7e81453e069b7c07a32a6b18" translate="yes" xml:space="preserve">
          <source>Run</source>
          <target state="translated">Запустить</target>
        </trans-unit>
        <trans-unit id="ecca71eb1169d48f8fa9222adafe9af3de6ce5fc" translate="yes" xml:space="preserve">
          <source>See &lt;a href=&quot;https://github.com/pmaxted/pycheops/tree/master/pycheops/examples/Notebooks&quot;&gt;pycheops/examples/Notebooks&lt;/a&gt; for examples.</source>
          <target state="translated">См. &lt;a href=&quot;https://github.com/pmaxted/pycheops/tree/master/pycheops/examples/Notebooks&quot;&gt;Примеры в pycheops / examples / Notebooks&lt;/a&gt; .</target>
        </trans-unit>
        <trans-unit id="99b86e0b87eb0ff4ba214261b76d678b96ae4b85" translate="yes" xml:space="preserve">
          <source>StarProperties(dataset.target) produces &amp;ldquo;Segmentation fault: 11&amp;rdquo;</source>
          <target state="translated">StarProperties (dataset.target) выдает &amp;laquo;Ошибка сегментации: 11&amp;raquo;.</target>
        </trans-unit>
        <trans-unit id="1e368921b9afa58875aa1742f46088b34f975150" translate="yes" xml:space="preserve">
          <source>This error message may appear when upgrading to pycheops version 0.8.0 or
later.  Two solutions have been found &amp;hellip;</source>
          <target state="translated">Это сообщение об ошибке может появиться при обновлении до версии pycheops 0.8.0 или новее. Было найдено два решения&amp;hellip;</target>
        </trans-unit>
        <trans-unit id="285ec850c11d78bac10f6bfa31b69a37f1b257c9" translate="yes" xml:space="preserve">
          <source>Troubleshooting</source>
          <target state="translated">Поиск и устранение неисправностей</target>
        </trans-unit>
        <trans-unit id="1d4d43cc6f3a833e0340a0d1794b6d7b9958657e" translate="yes" xml:space="preserve">
          <source>Use</source>
          <target state="translated">Использовать</target>
        </trans-unit>
        <trans-unit id="475d865beac29b2c1d2de1cd15fe7a2d1bdc5db3" translate="yes" xml:space="preserve">
          <source>You are running the wrong version of python, e.g., anaconda2 instead of anaconda3</source>
          <target state="translated">Вы используете не ту версию питона,например,анаконду2 вместо анаконды3.</target>
        </trans-unit>
        <trans-unit id="d4cea94a9a055ac104e40fad44b010f63c0df2b2" translate="yes" xml:space="preserve">
          <source>pip install pybind11</source>
          <target state="translated">трубопроводный монтажник pybind11</target>
        </trans-unit>
        <trans-unit id="c955f7739ac2d9cac257f30a9e97b736b714c205" translate="yes" xml:space="preserve">
          <source>pip install pycheops</source>
          <target state="translated">установочные пикеопы</target>
        </trans-unit>
        <trans-unit id="cb7fe1dadc11c7273b873e433cdaa196b5e0038c" translate="yes" xml:space="preserve">
          <source>then try again</source>
          <target state="translated">затем повторить попытку</target>
        </trans-unit>
        <trans-unit id="2b4d0ad41616227d6aadd4f0785e73f1aca07a81" translate="yes" xml:space="preserve">
          <source>to install.</source>
          <target state="translated">на установку.</target>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
