<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="en" target-language="es" datatype="htmlbody" original="https://pypi.org/project/pycheops/">
    <body>
      <group id="pycheops">
        <trans-unit id="f1603d521808f158186cc68afb235430e8216c34" translate="yes" xml:space="preserve">
          <source>&amp;ldquo;No matching distribution found for matplotlib&amp;gt;3,2 (from pycheops)&amp;rdquo;</source>
          <target state="translated">&quot;No se encontr&amp;oacute; ninguna distribuci&amp;oacute;n coincidente para matplotlib&amp;gt; 3,2 (de pycheops)&quot;</target>
        </trans-unit>
        <trans-unit id="5dd5599aa0661138fac4e54a2ad7d4390c685267" translate="yes" xml:space="preserve">
          <source>&amp;ldquo;TypeError: &amp;lsquo;str&amp;rsquo; object is not callable&amp;rdquo; in animate frames</source>
          <target state="translated">&quot;TypeError: el objeto 'str' no es invocable&quot; en marcos animados</target>
        </trans-unit>
        <trans-unit id="930634090215011d3fafe673f03eca7ee4c23fb6" translate="yes" xml:space="preserve">
          <source>&amp;ldquo;conda update &amp;ndash;all&amp;rdquo; then &amp;ldquo;pip install pycheops &amp;ndash;upgrade&amp;rdquo;</source>
          <target state="translated">&quot;Conda update &amp;ndash;todos&quot; y luego &quot;pip install pycheops &amp;ndash;upgrade&quot;</target>
        </trans-unit>
        <trans-unit id="eb810f9c8fe03f2f3eac98788ce4ab3f34b6d152" translate="yes" xml:space="preserve">
          <source>&amp;ldquo;pip install matplotlib &amp;ndash;upgrade&amp;rdquo; then &amp;ldquo;pip install pycheops &amp;ndash;upgrade&amp;rdquo;</source>
          <target state="translated">&amp;ldquo;Pip install matplotlib &amp;ndash;upgrade&amp;rdquo; y luego &amp;ldquo;pip install pycheops &amp;ndash;upgrade&amp;rdquo;</target>
        </trans-unit>
        <trans-unit id="763e13fbb5e11a148c6e753ca9e4e3d0b8cbf233" translate="yes" xml:space="preserve">
          <source>CHEOPS light curve analysis software</source>
          <target state="translated">El software de análisis de la curva de luz CHEOPS</target>
        </trans-unit>
        <trans-unit id="3414d1ef796b45b8b78636cc7dc0d00485e20ff9" translate="yes" xml:space="preserve">
          <source>For discussion and announcements, please join the &lt;a href=&quot;https://groups.google.com/forum/#!forum/pycheops&quot;&gt;pycheops google group&lt;/a&gt;</source>
          <target state="translated">Para discusiones y anuncios, &amp;uacute;nase al &lt;a href=&quot;https://groups.google.com/forum/#!forum/pycheops&quot;&gt;grupo de google de pycheops&lt;/a&gt;</target>
        </trans-unit>
        <trans-unit id="1605b302b4f14fef72c2f2b293539ce45c4cec5b" translate="yes" xml:space="preserve">
          <source>Install &amp;ldquo;pillow&amp;rdquo;, e.g., conda install pillow.</source>
          <target state="translated">Instale &quot;almohada&quot;, por ejemplo, conda install pillow.</target>
        </trans-unit>
        <trans-unit id="7ab62122bb2dfe3b61ac8bfc91d110f16ce0d7b4" translate="yes" xml:space="preserve">
          <source>Installation fails with &amp;ldquo;ModuleNotFoundError: No module named &amp;lsquo;pybind11&amp;rsquo;&amp;rdquo;</source>
          <target state="translated">La instalaci&amp;oacute;n falla con &quot;ModuleNotFoundError: No hay m&amp;oacute;dulo llamado 'pybind11'&quot;</target>
        </trans-unit>
        <trans-unit id="e085eda5031b722f6498d726b7bcf078ef13852c" translate="yes" xml:space="preserve">
          <source>Python package for the analysis of light curves from the &lt;a href=&quot;http://cheops.unibe.ch/&quot;&gt;ESA CHEOPS mission&lt;/a&gt;.</source>
          <target state="translated">Paquete Python para el an&amp;aacute;lisis de curvas de luz de la &lt;a href=&quot;http://cheops.unibe.ch/&quot;&gt;misi&amp;oacute;n CHEOPS&lt;/a&gt; de la ESA .</target>
        </trans-unit>
        <trans-unit id="b1b392607deaf29a7e81453e069b7c07a32a6b18" translate="yes" xml:space="preserve">
          <source>Run</source>
          <target state="translated">Corre</target>
        </trans-unit>
        <trans-unit id="ecca71eb1169d48f8fa9222adafe9af3de6ce5fc" translate="yes" xml:space="preserve">
          <source>See &lt;a href=&quot;https://github.com/pmaxted/pycheops/tree/master/pycheops/examples/Notebooks&quot;&gt;pycheops/examples/Notebooks&lt;/a&gt; for examples.</source>
          <target state="translated">Consulte &lt;a href=&quot;https://github.com/pmaxted/pycheops/tree/master/pycheops/examples/Notebooks&quot;&gt;pycheops / examples / Notebooks&lt;/a&gt; para ver ejemplos.</target>
        </trans-unit>
        <trans-unit id="99b86e0b87eb0ff4ba214261b76d678b96ae4b85" translate="yes" xml:space="preserve">
          <source>StarProperties(dataset.target) produces &amp;ldquo;Segmentation fault: 11&amp;rdquo;</source>
          <target state="translated">StarProperties (dataset.target) produce &quot;Fallo de segmentaci&amp;oacute;n: 11&quot;</target>
        </trans-unit>
        <trans-unit id="1e368921b9afa58875aa1742f46088b34f975150" translate="yes" xml:space="preserve">
          <source>This error message may appear when upgrading to pycheops version 0.8.0 or
later.  Two solutions have been found &amp;hellip;</source>
          <target state="translated">Este mensaje de error puede aparecer al actualizar a la versi&amp;oacute;n 0.8.0 o posterior de pycheops. Se han encontrado dos soluciones ...</target>
        </trans-unit>
        <trans-unit id="285ec850c11d78bac10f6bfa31b69a37f1b257c9" translate="yes" xml:space="preserve">
          <source>Troubleshooting</source>
          <target state="translated">Solución de problemas</target>
        </trans-unit>
        <trans-unit id="1d4d43cc6f3a833e0340a0d1794b6d7b9958657e" translate="yes" xml:space="preserve">
          <source>Use</source>
          <target state="translated">Utilice</target>
        </trans-unit>
        <trans-unit id="475d865beac29b2c1d2de1cd15fe7a2d1bdc5db3" translate="yes" xml:space="preserve">
          <source>You are running the wrong version of python, e.g., anaconda2 instead of anaconda3</source>
          <target state="translated">Estás ejecutando la versión equivocada de pitón,por ejemplo,anaconda2 en lugar de anaconda3</target>
        </trans-unit>
        <trans-unit id="d4cea94a9a055ac104e40fad44b010f63c0df2b2" translate="yes" xml:space="preserve">
          <source>pip install pybind11</source>
          <target state="translated">pip instalar pybind11</target>
        </trans-unit>
        <trans-unit id="c955f7739ac2d9cac257f30a9e97b736b714c205" translate="yes" xml:space="preserve">
          <source>pip install pycheops</source>
          <target state="translated">pip instalar pycheops</target>
        </trans-unit>
        <trans-unit id="cb7fe1dadc11c7273b873e433cdaa196b5e0038c" translate="yes" xml:space="preserve">
          <source>then try again</source>
          <target state="translated">...y luego intentarlo de nuevo.</target>
        </trans-unit>
        <trans-unit id="2b4d0ad41616227d6aadd4f0785e73f1aca07a81" translate="yes" xml:space="preserve">
          <source>to install.</source>
          <target state="translated">para instalar.</target>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
